app:
  # App name
  name: "DGStuff"
  # App description
  description: "DGStuff is a platform for selling digital goods"
  # App logo URL
  logo_url: "https://dgstuff.com/logo.png"

database:
  # Database provider. supported: sqlite, mysql, postgres
  provider: sqlite
  # Database URL. support sqlite, mysql, postgres.
  # Example:
  # sqlite: file.db
  # mysql: user:password@tcp(host:port)/database
  # postgres: user:password@host:port/database
  url: ./dgstuff.db

stock:
  # Secret key to encrypt and decrypt the stock values
  # This is generated random key. but you can change it to your own secret key
  secret_key: "<random-key>"

transaction:
  # Prefix to generate the transaction ID
  # Example: TRXASDJKL690
  prefix: "TRX"

payment:
  # Expiration time for the payment invoice
  # Example: 1h
  expiration_time: 1h
  provider:
    xendit:
      api_key: "<xendit-api-key>"
      callback_token: "<xendit-callback-token>"